#!/usr/bin/env node
import { createLaunchVideo, withDefaults } from "./pipeline.js";
import { summaryLines } from "../output/index.js";
import type { LaunchOptions, ProgressEvent } from "../types.js";

const HELP = `frameo — one command: a 30-second launch video from a repository's real UI

Usage:
  frameo <repository-url-or-path> [options]

Options:
  --duration <sec>        15–30, default 30
  --format <f>            landscape | vertical | square   (aliases: 16:9, 9:16, 1:1)
  --tone <preset|text>    polished | cinematic | minimal | playful | technical | app-store | bold, or freeform
  --platform <p>          linkedin | x | instagram-reel | youtube-short | product-hunt
  --style <text>          extra creative direction
  --audience <text>       target audience (default: inferred)
  --voice                 reserved: narration is not generated by this build (flag recorded)
  --no-music              disable the music bed
  --no-sfx                disable sound effects
  --no-run                skip running the app (static + source-derived visuals only)
  --no-install            never install dependencies
  --no-render             build everything but do not render
  --quality <q>           draft | looks | delivery (default looks)
  --branch <name>         git branch
  --out <dir>             output directory (default frameo-output/ or timestamped)
  --workspace <dir>       where to clone (default OS temp)
  --max-screens <n>       maximum routes to capture (default 10)
  --title <name>          override the product name
  --json                  print the final result as JSON
  -h, --help
`;

interface ParsedArgs {
  positional: string[];
  flags: Record<string, string | boolean>;
}

export function parseArgs(argv: string[]): ParsedArgs {
  const positional: string[] = [];
  const flags: Record<string, string | boolean> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const [k, inline] = a.slice(2).split("=", 2);
      if (inline !== undefined) flags[k] = inline;
      else if (k.startsWith("no-")) flags[k] = true;
      else if (BOOLEAN_FLAGS.has(k)) flags[k] = true;
      else if (i + 1 < argv.length && !argv[i + 1].startsWith("--")) flags[k] = argv[++i];
      else flags[k] = true;
    } else if (a === "-h") flags.help = true;
    else positional.push(a);
  }
  return { positional, flags };
}

const BOOLEAN_FLAGS = new Set(["voice", "json", "help", "verbose"]);

export function optionsFromFlags(repo: string, flags: Record<string, string | boolean>): Partial<LaunchOptions> & { repositoryUrl: string } {
  const str = (k: string) => (typeof flags[k] === "string" ? (flags[k] as string) : undefined);
  const num = (k: string) => (str(k) !== undefined ? Number(str(k)) : undefined);
  const fmtRaw = str("format");
  const format = fmtRaw ? ({ "16:9": "landscape", "9:16": "vertical", "1:1": "square", landscape: "landscape", vertical: "vertical", square: "square", portrait: "vertical", horizontal: "landscape" } as Record<string, LaunchOptions["format"]>)[fmtRaw] : undefined;
  return {
    repositoryUrl: repo,
    branch: str("branch"),
    duration: num("duration"),
    format,
    tone: str("tone"),
    platform: str("platform") as LaunchOptions["platform"] | undefined,
    style: str("style"),
    targetAudience: str("audience") ?? str("target-audience"),
    voice: flags.voice === true,
    music: flags["no-music"] ? false : undefined,
    sfx: flags["no-sfx"] ? false : undefined,
    run: flags["no-run"] ? false : undefined,
    install: flags["no-install"] ? false : undefined,
    render: flags["no-render"] ? false : undefined,
    quality: str("quality") as LaunchOptions["quality"] | undefined,
    outputDir: str("out") ?? str("output"),
    workspaceDir: str("workspace"),
    maxScreens: num("max-screens"),
    title: str("title"),
    verbose: flags.verbose === true,
  };
}

const ICON: Record<ProgressEvent["status"], string> = { start: "→", done: "✓", skip: "–", warn: "!", fail: "✗" };

export function printProgress(e: ProgressEvent): void {
  process.stderr.write(`${ICON[e.status]} ${e.message}\n`);
}

async function main(): Promise<void> {
  const { positional, flags } = parseArgs(process.argv.slice(2));
  if (flags.help || !positional.length) {
    process.stdout.write(HELP);
    process.exit(flags.help ? 0 : 1);
  }
  const target = positional[0];
  const partial = optionsFromFlags(target, flags);
  const started = Date.now();
  const result = await createLaunchVideo(partial, { report: flags.json ? undefined : printProgress });
  const lines = summaryLines({ options: withDefaults(partial), repo: result.repositoryAnalysis, runtime: result.runtimeAnalysis, ui: result.uiAnalysis, dna: result.productDNA, storyboard: result.storyboard, render: result.render, files: result.files, shareCopyText: "" }, result.qualityGate);
  if (flags.json) {
    process.stdout.write(JSON.stringify({ ok: result.ok, outputDir: result.outputDir, summary: lines, render: result.render, qualityGate: result.qualityGate, files: result.files }, null, 2) + "\n");
  } else {
    process.stdout.write("\n" + lines.join("\n") + "\n\n");
    process.stdout.write(`Your Frameo launch package is ready: ${result.outputDir}  (${((Date.now() - started) / 1000).toFixed(0)}s)\n`);
    if (result.render.status === "rendered") process.stdout.write(`Video:  ${result.render.videoPath}\nPoster: ${result.render.posterPath}\n`);
    else process.stdout.write(`Video not rendered: ${result.render.reason}\n`);
    const failures = result.qualityGate.checks.filter((c) => !c.ok);
    if (failures.length) process.stdout.write(`Quality gate notes:\n${failures.map((f) => `  ${f.severity === "error" ? "✗" : "!"} ${f.id}: ${f.message}`).join("\n")}\n`);
  }
  process.exit(result.ok ? 0 : 2);
}

const invokedDirectly = (process.argv[1] && /cli\.(ts|js)$/.test(process.argv[1])) || process.argv[1]?.endsWith("frameo.js") || process.argv[1]?.endsWith("frameo");
if (invokedDirectly) {
  main().catch((err) => {
    process.stderr.write(`✗ ${(err as Error).stack ?? err}\n`);
    process.exit(1);
  });
}
